apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

resources:
- deploy.yaml

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: kustomize-nginx
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
